POST http://localhost:8080/contacts
Content-Type: application/json

{
  "name": "Charles Eimer",
  "email": "c.eimer@me.com",
  "title": "Developer",
  "phoneNumber": "514-555-1234",
  "location": "Montreal, Canada",
  "status": "Inactive"
}

### GET
GET  http://localhost:8080/contacts/1

### DELETE
DELETE http://localhost:8080/contacts/1